import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/components/Header";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer";
import FadeMenu from "@/components/material";
export default function Bluekid() {
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="blog-page">
      <header>
          <div className="navbar navbar-grid">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div id="mySidepanel" className="sidepanel">
              <a
                href="javascript:void(0)"
                className="closebtn"
                onClick={() => closeNav()}
              ></a>
              <a className="no--border" href="#home">
                Home
              </a>
              <a href="#" className="nav-link">
                Pages
              </a>
              <a href="#" className="nav-link">
                Events{" "}
              </a>
              <a href="#" className="nav-link">
                Blog
              </a>
              <a href="#" className="nav-link">
                Shop
              </a>
              <a href="#" className="nav-link">
                Landing
              </a>
            </div>
            <button className="openbtn open-btn-grid" onClick={() => openNav()}>
              ...
            </button>
          </div>
          <div className="navbar navbar--ROP">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div className="nav-links">
            <ul className = "no-bullets">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="#"><FadeMenu /></Link>
              </li>
              <li>
                <Link href="/Blog">Blog</Link>
              </li>

              <li>
                <Link href="/shop">Shop</Link>
                 </li> 
              <li>
                <Link href="/grid-view">Grid Home</Link>
              </li>
              <li>
                <Link href="/Events">Events</Link>
              </li>
            </ul>
          </div>
          </div>
        </header>
      <div className="kid-image blue-kid">
        <img src="/images/blog/blue-kid.jpg" alt="image" />
      </div>
      <div className="blog--flx">
        <div className="right-flx">
          <h2>Make Their Dreams Come to Life </h2>
          <div className="date-flx">
            <div className="day-blog">
              <p>May 25, 2020 </p>
            </div>
            <div className="category">
              <p>Cute / Parents</p>
            </div>
          </div>
          <div className="blog-para">
            <p>Lorem ipsum dolor sit amet, est id mundi iudico maiestatis, ad amet zril mel. Probatus facilisi velinaro no. Ex putant hendrerites comple ctitur sed, legimus noluisse an mei, in menandri in corrupte eos. Et justo docendi eam, dicant facet an sit. Odio everti vis ex, nec eu nobis impe dit. In pro oratio omne, no magna idque sed. Augue delenit iracundia at usu, sit inani con sequat ea. His a facer labitur ut, ullum maiorum splendide per ne, nam viderer fierent in. Vi sale ornatus at. Autem tritani suscipiantur ei has hen reritas. Ad vis diam tincidunt sadipscing.</p>
          </div>
          <div className="blog-img-flx">
        <img src="/images/blog/blog1.jpg" alt="image" />
        <img src="/images/blog/blog2.jpg" alt="image" />
        <img src="/images/blog/blog3.jpg" alt="image" />
        <img src="/images/blog/blog4.jpg" alt="image" />
        <img src="/images/blog/blog5.jpg" alt="image" />
        <img src="/images/blog/blog6.jpg" alt="image" />
          </div>
          <div className="new-para-blog">
            <p>Cum consul noster nonumes eu, ne vis elitr reprimique. Eam te oportere conclusionemque, ius ad oblique eripuit, per ut tincidunt appell antur. Elaborare appellantur referrentur at vel, et nec quot integre accusata. Mel in aeque nonumy delenit, lobortis antiopam ex eum. An has eros laboramus sententiae. Lorem ipsum dolor sit amet, est id mundi iudico maiestatis, ad amet zril mel. Probatus facilisi vel no. Exo putant hendrerit complectitur sed, legimus noluisse anmei, in menandri incorrup eos legimus noluisse an mei probatu. Vel eu elit consula.</p>
          <p className="red-para"> "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullam corper matti, pul dapibus leo. An sit unum dicant, ei eos ali quam fastidii. Ad eos oratio dolorem.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo. Sea alienum senserit at, vel ad ullum adversarium, no sit consulatu delicatissimi. Vel te quas consul iriure, an cum tota iudico doming. Oratio option labitur sea eu, debet ceteros ad pri. Te quot modus laboramus sea ullum. Duo ex tempor viderer.</p>
          <p>Eum alterum prodesset ut, mei at stet semper. Et mea alii vitae primis. No has esse soluta. Augu delenit iracundia at usu, sit inani conse quat ea. His facer labitur ut, ullum maiorum splendide per ne, nam viderer fierent in his facer labitur ut esse soluta.</p>
          </div>
{/* <div className="author">
  <div className="author-name">
  <h5>Petra Lane </h5>
  </div>
  <div className="author-para">
  Augue delenit iracundia at usu, sit inani consequat ea. His facer labitur ut, ullum maiorum.
  </div>
  <div className="blog-icons">
    <a href=""><i className="fa fa-facebook" aria-hidden="true"></i></a>
    <a href=""><i className="fa fa-twitter" aria-hidden="true"></i></a>
    <a href=""><i className="fa fa-instagram" aria-hidden="true"></i></a>

  </div>
</div> */}
        </div>
      </div>
      </main>
      <div className="Footer">
        <Footer />
      </div>
    </>
  );
}
