import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/components/Header";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer";
export default function Blog() {
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="blog">
        <header>
          <div className="header">
            <Header />
          </div>
        </header>
        <div class="my-flex-container blog-flex">
        <div class="my-card my--card__item">
    <img src="/images/grid-home/kid-3.jpg " alt="kid" />
    <div class="my-card-content">
      <h2>Always Be There for Your Child </h2>
      <div className="card--content--flexbox">
      <p class="my-date">June 5 2020</p>
      <p class="my-play">Play</p>
      </div>
    </div>
  </div>
  
  <div class="my-card my--card__item">
  <img src="/images/grid-home/kid-2.jpg" alt="kid" />
    <div class="my-card-content">
      <h2>Doing What They Know and Love </h2>
      <div className="card--content--flexbox">
      <p class="my-date">June 5 2020</p>
      <p class="my-play">Play</p>
      </div>
    </div>
    </div>
    <div class="my-card my--card__item">
   <img src="/images/grid-home/kid-1.jpg" alt="kid" />
    <div class="my-card-content">
      <h2>Come With Us and Have More Fun</h2>
      <div className="card--content--flexbox">
      <p class="my-date">June 5 2020</p>
      <p class="my-play">Play</p>
      </div>
    </div>
  </div>


 
</div>
      </main>

      <div className="footer-sec">
        <Footer />
      </div>
      </>
  );
}