import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import dynamic from "next/dynamic";

export default function GridHome() {
  const myStyles = {
    backgroundColor: '#C3E1DB',
  }
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="body">
      <header>
        <nav>
          <div className="navbar navbar-grid">
            <div className="logo">
              <Link href="/">
                <img src="images/homepage/header-logo.png" alt="Logo" />
              </Link>
            </div>

            <div id="mySidepanel" className="sidepanel">
              <a href="javascript:void(0)" className="closebtn" onClick={() => closeNav()}>×</a>
              <a className="no--border" href="#home">Home</a>
              <a href="#" className="nav-link">Pages</a>
              <a href="#" className="nav-link">Events </a>
              <a href="#" className="nav-link">Blog</a>
              <a href="#" className="nav-link">Shop</a>
              <a href="#" className="nav-link">Landing</a>
            </div>
            <button className="openbtn open-btn-grid" onClick={() => openNav()}>...</button>

            <div className="nav-links">
              <ul className="no-bullets">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/pages">Pages</Link>
                </li>
                <li>
                  <Link href="/events">Events</Link>
                </li>
                <li>
                  <Link href="/blog">Blog</Link>
                </li>
                <li>
                  <Link href="/shop">Shop</Link>
                </li>
                <li>
                  <Link href="/landing">Landing</Link>
                </li>
                <li>
                  <Link href="/grid-view">Grid View</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div className="qodef-pricing-plans">
       <p> <span className="sub-heading">Check Out Our</span></p>
        <h1><span className="first-color">Event</span> <span className="second-color">Pricing</span> <span className="third-color">Plans</span></h1>
        <div className="pricing-flexbox">
        <div className="pricing-item pricing-item-1">
          <div className="pricing-image">
        <img src="images/grid-home/36$.png" alt="your-image-description"/>
        <div className="pricing-image-text">
          <h2 className="no-background ">36$</h2></div> 
          </div>
  <h2 className="no-background ">Garden 1Hr</h2>
  <p className="no-background ">Te sint tincidu accomo</p>
  <button>Buy Now</button>
        </div>
        <div className="pricing-item pricing-item-2">
        <div className="pricing-image ">
        <img src="images/grid-home/202$.png" alt="your-image-description"/>
        <div className="pricing-image-text">
          <h2>202$</h2></div> 
          </div>
  <h2>Mini Party</h2>
  <p>Te sint tincidu accomo</p>
  <button>Buy Now</button>
        </div>
        <div className="pricing-item pricing-item-3">
        <div className="pricing-image">
        <img src="images/grid-home/161$.png" alt="your-image-description"/>
        <div className="pricing-image-text">
          <h2>161$</h2></div> 
          </div>
  <h2>Art Class</h2>
  <p>Te sint tincidu accomo</p>
  <button>Buy Now</button>
          </div>
        </div>

      </div>
<div className="element-momenter">
<img src="images/grid-home/robot.png" alt="image" />
<h3>Welcome</h3>
<h2>Playroom</h2>
<p className="p-center">No homero evertitur vim, sea et impedit inimicus hon estatis afacit.</p>
<div className="grid-social-icons">
         <div className="grid-icon"><img src="images/icons/facebook.png" alt="facebook"/>
           </div>
            <div className="grid-icon"><img src="images/icons/twitter.png" alt="twitter"/>
           </div>
           <div className="grid-icon"> <img src="images/icons/instagram.png" alt="instagram"/>
           </div>

         </div>

</div>

      <footer>
        <div className="footer-flexbox">
          <div className="qodef-first-flexbox">
            <a href="#">
          <p> <strong class="no-background">  About </strong></p>

            </a>
            <a href="#">
           <p>
            <strong class="no-background">
            Shop
            </strong>
           </p>
            </a>
            <a href="#">
           <p><strong class="no-background">Calender </strong> </p>
            </a>
          </div>
          <div className="qodef-mid-footer">
            <p><span>© 2023 </span> <span className="bold"><a href=""><strong> Qode Interactive </strong></a></span><span>, All Rights Reserved</span></p>
          </div>
          <div className="qodef-last-flexbox">
            <a href="#">
           <p> <strong class="no-background">Event</strong></p>
            </a>
            <a href="#">
           <p><strong class="no-background">Story</strong></p>
            </a>
            <a href="#">
           <p><strong class="no-background">Contacts</strong></p>
            </a>
          </div>
        </div>
      </footer>
      </ main>
 
    </>
  );
}
