import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import dynamic from "next/dynamic";
import Section1 from '../components/swiper';
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="nav-header">
    <Header />
        </div>
      <Section1></Section1> 
      <div className="fun-center">
        <h2>Welcome To</h2>
        <h1><span className="first-color">Kid's</span> <span className="second-color">Fun</span> <span className="third-color">Center</span></h1>
        <div className="fun--center--flexbox">
          <div className="flexbox open-session">
            <img src="/images/fun-center/open-sessions.jpg" alt="open-sessions image" />
            <h3>Open Sessions</h3>
            <p>Non dipopulo ancilae, epic palo eam erasmus se ergo no am.</p>
          </div>
          <div className="flexbox">
            <img src="/images/fun-center/class-trips.jpg" alt="class-trips image" />
            <h3>Class Trips</h3>
            <p>Non dipopulo ancilae, epic palo eam erasmus se ergo no am.</p>
          </div>
          <div className="flexbox">
            <img src="/images/fun-center/birthday-parties.jpg" alt="birthday party image" />
            <h3>Birthday Party's</h3>
            <p>Non dipopulo ancilae, epic palo eam erasmus se ergo no am.</p>
          </div>
        </div>
      </div>
      <div className="new-events">
        <div className="event-video">
          <div className="event-image kids-image">
      <div className="elementary-image">
        <img className="blank"src="/images/background-images/pattern.png" alt="aa" />
      </div>
          <img src="/images/fun-center/events.jpg" alt="video"/> 
          </div>
          <a className= "play--button"itemprop="url" href="https://vimeo.com/13993501" target="_self" data-type="iframe">
           <img class="qodef-m-image" src="https://playroom.qodeinteractive.com/wp-content/plugins/playroom-core/inc/shortcodes/video-button/assets/img/video-button-play.png" alt="Play icon image"></img>
          </a>
        </div>
        <div className="event-text">
          <h2>New Video</h2>
          <h1><span className="first-color">New</span> <span className="second-color">Approach To</span> <span className="third-color">Fun</span></h1>
          <p>Tollit referrentur contentiones an sed. Ius tacimates defini tione, quoprimatum dicunt labitur te. Te debet tibique.</p>
          <div className="find-events">
            <a href="https://playroom.qodeinteractive.com/events/month/">
           <span class="find-events--text">Find Events</span></a>
          </div>
        </div>
        <div className="elementary-image">
        <img className="blank" src="/images/background-images/pattern-2.png" alt="aa" />
      </div>
      </div>
    </main>
    </>
  );
}
