import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import dynamic from "next/dynamic";
import Section1 from '../components/swiper';

export default function Home() {
  return (
    <>
      <Head>
        <title>playroom-kids Theme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <nav>
        <div className="navbar">
          <div className="logo">
            <Link href="/">
              <img src="images/homepage/header-logo.png" alt="Logo" />
            </Link>
          </div>
          <div className="nav-links">
            < ul className = "no-bullets">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/pages">Pages</Link>
              </li>
              <li>
                <Link href="/events">Events</Link>
              </li>
              <li>
                <Link href="/blog">Blog</Link>
              </li>
              <li>
                <Link href="/shop">Shop</Link>
              </li>
              <li>
                <Link href="/landing">Landing</Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <Section1></Section1> 
      </main>
    </>
  );
}
